# Generated by Django 4.0.3 on 2022-03-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='drinks_allergies',
            new_name='allergies',
        ),
    ]
